// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trustme.MigrationConsole;

#nullable disable

namespace Trustme.MigrationConsole.Migrations
{
    [DbContext(typeof(TrustmeTestContext))]
    partial class TrustmeTestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trustme.MigrationConsole.Candidate", b =>
                {
                    b.Property<Guid>("DbKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrchestrationStepDbKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubJourneyDbKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubJourneyReferenceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasKey("DbKey");

                    b.HasIndex("OrchestrationStepDbKey");

                    b.HasIndex("SubJourneyDbKey");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("Trustme.MigrationConsole.OrchestrationStep", b =>
                {
                    b.Property<Guid>("DbKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrchestrationStepJourney")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("DbKey");

                    b.ToTable("OrchestrationSteps", (string)null);

                    b.HasDiscriminator<string>("OrchestrationStepJourney").HasValue("OrchestrationStep");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Trustme.MigrationConsole.SubJourney", b =>
                {
                    b.Property<Guid>("DbKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyDbKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("DbKey");

                    b.HasIndex("PolicyDbKey");

                    b.ToTable("SubJourneys", (string)null);
                });

            modelBuilder.Entity("Trustme.MigrationConsole.TrustFrameworkPolicy", b =>
                {
                    b.Property<Guid>("DbKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DbKey");

                    b.ToTable("TrustFrameworkPolicies", (string)null);
                });

            modelBuilder.Entity("Trustme.MigrationConsole.UserJourney", b =>
                {
                    b.Property<Guid>("DbKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssuranceLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyDbKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DbKey");

                    b.HasIndex("PolicyDbKey");

                    b.ToTable("UserJourneys", (string)null);
                });

            modelBuilder.Entity("Trustme.MigrationConsole.OrchestrationStepSubJourney", b =>
                {
                    b.HasBaseType("Trustme.MigrationConsole.OrchestrationStep");

                    b.Property<Guid>("JourneyDbKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("JourneyDbKey");

                    b.ToTable("OrchestrationSteps", (string)null);

                    b.HasDiscriminator().HasValue("OrchestrationStepSubJourney");
                });

            modelBuilder.Entity("Trustme.MigrationConsole.OrchestrationStepUserJourney", b =>
                {
                    b.HasBaseType("Trustme.MigrationConsole.OrchestrationStep");

                    b.Property<Guid>("JourneyDbKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("JourneyDbKey");

                    b.ToTable("OrchestrationSteps", null, t =>
                        {
                            t.Property("JourneyDbKey")
                                .HasColumnName("OrchestrationStepUserJourney_JourneyDbKey");
                        });

                    b.HasDiscriminator().HasValue("OrchestrationStepUserJourney");
                });

            modelBuilder.Entity("Trustme.MigrationConsole.Candidate", b =>
                {
                    b.HasOne("Trustme.MigrationConsole.OrchestrationStep", null)
                        .WithMany("JourneyList")
                        .HasForeignKey("OrchestrationStepDbKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trustme.MigrationConsole.SubJourney", "SubJourney")
                        .WithMany("Candidates")
                        .HasForeignKey("SubJourneyDbKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubJourney");
                });

            modelBuilder.Entity("Trustme.MigrationConsole.SubJourney", b =>
                {
                    b.HasOne("Trustme.MigrationConsole.TrustFrameworkPolicy", "Policy")
                        .WithMany("SubJourneys")
                        .HasForeignKey("PolicyDbKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Trustme.MigrationConsole.UserJourney", b =>
                {
                    b.HasOne("Trustme.MigrationConsole.TrustFrameworkPolicy", "Policy")
                        .WithMany("UserJourneys")
                        .HasForeignKey("PolicyDbKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Trustme.MigrationConsole.OrchestrationStepSubJourney", b =>
                {
                    b.HasOne("Trustme.MigrationConsole.SubJourney", "Journey")
                        .WithMany("OrchestrationSteps")
                        .HasForeignKey("JourneyDbKey")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Trustme.MigrationConsole.OrchestrationStepUserJourney", b =>
                {
                    b.HasOne("Trustme.MigrationConsole.UserJourney", "Journey")
                        .WithMany("OrchestrationSteps")
                        .HasForeignKey("JourneyDbKey")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Trustme.MigrationConsole.OrchestrationStep", b =>
                {
                    b.Navigation("JourneyList");
                });

            modelBuilder.Entity("Trustme.MigrationConsole.SubJourney", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("OrchestrationSteps");
                });

            modelBuilder.Entity("Trustme.MigrationConsole.TrustFrameworkPolicy", b =>
                {
                    b.Navigation("SubJourneys");

                    b.Navigation("UserJourneys");
                });

            modelBuilder.Entity("Trustme.MigrationConsole.UserJourney", b =>
                {
                    b.Navigation("OrchestrationSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
